name: Github Actions
on:
  push:
    branches: [master]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: jiro4989/setup-nim-action@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        nim-version: stable
    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get install -y curl ca-certificates libpcre3-dev
    - name: Install nimby
      run: nimble install nimby -y
    - name: Cache nimby packages
      uses: actions/cache@v4
      with:
        path: ~/.nimby
        key: ${{ runner.os }}-nimby-${{ hashFiles('nimby.lock') }}
        restore-keys: |
          ${{ runner.os }}-nimby-
    - run: nimby sync -g nimby.lock
    - run: make check
    - run: make test
